#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_NAV_REPO = Path(os.environ.get("NAVSTRATEGIES_REPO", "~/repos/navstrategies")).expanduser()

try:
    import nbformat
    from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook
    from playwright.sync_api import Page, sync_playwright
except ModuleNotFoundError:
    fallback_python = DEFAULT_NAV_REPO / ".venv" / "bin" / "python"
    if fallback_python.exists() and os.environ.get("MORDOR_GATE3A_REEXEC") != "1":
        env = os.environ.copy()
        env["MORDOR_GATE3A_REEXEC"] = "1"
        os.execve(str(fallback_python), [str(fallback_python), __file__, *sys.argv[1:]], env)
    raise


DONE_MARKER = "MORDOR_GATE3A_DONE"
DEFAULT_CHROMIUM = "/usr/bin/chromium-browser"

STARTING_NOTEBOOK_DENYLIST = (
    "navstrategies.utilities.hot_universe",
    "load_hot_universe",
    "cache_status",
    "pivot",
    "rank(",
    ".rank",
    "long_mask",
    "short_mask",
    "weights",
    "strategy_return",
    "matplotlib",
    "plt",
    ".plot(",
    '["AAPL", "NVDA", "SOXL", "KORU"]',
    "['AAPL', 'NVDA', 'SOXL', 'KORU']",
)

GENERATED_MARKER = "Mordor generated"


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def run(
    command: list[str],
    *,
    cwd: Path | None = None,
    timeout: float = 30.0,
    input_text: str | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=str(cwd) if cwd else None,
        input=input_text,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True, default=str), encoding="utf-8")


def append_jsonl(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, sort_keys=True, default=str) + "\n")


def create_thin_starting_notebook(nav_repo: Path, stamp: str) -> Path:
    scratch_dir = nav_repo / "notebooks" / "qa_scratch"
    scratch_dir.mkdir(parents=True, exist_ok=True)
    notebook_path = scratch_dir / f"mordor_gate3a_agent_generated_{stamp}.ipynb"
    bootstrap = f"""from mordornotebook import attach

mordor = attach(
    repo={str(nav_repo)!r},
    goal="Gate 3A agent-generated navstrategies notebook QA",
    notebook_path={str(notebook_path)!r},
)
mordor.register(
    "gate3a_seed",
    {{"purpose": "bootstrap only", "note": "analysis cells must be generated by Codex through Mordor"}},
)
mordor.panel()
"""
    nb = new_notebook(
        cells=[
            new_markdown_cell(
                "# Mordor Gate 3A QA\n\n"
                "Thin bootstrap only. Codex/Mordor must inspect context, author the analysis cells, "
                "insert them into this live notebook, and leave rendered evidence."
            ),
            new_code_cell(bootstrap),
        ],
        metadata={
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
        },
    )
    nbformat.write(nb, notebook_path)
    return notebook_path


def notebook_source_text(path: Path) -> str:
    nb = nbformat.read(path, as_version=4)
    return "\n\n".join(str(cell.get("source", "")) for cell in nb.cells)


def validate_starting_notebook(path: Path) -> list[str]:
    source = notebook_source_text(path)
    failures = [token for token in STARTING_NOTEBOOK_DENYLIST if token in source]
    nb = nbformat.read(path, as_version=4)
    if len(nb.cells) != 2:
        failures.append(f"expected exactly 2 bootstrap cells, found {len(nb.cells)}")
    if not nb.cells or nb.cells[0].cell_type != "markdown":
        failures.append("first cell is not markdown")
    if len(nb.cells) < 2 or nb.cells[1].cell_type != "code":
        failures.append("second cell is not code")
    return failures


def prompt_text(nav_repo: Path, mordorctl: Path, session_name: str, stamp: str) -> str:
    temp_dir = f"/tmp/mordor_gate3a_{stamp}"
    return f"""You are operating inside a live navstrategies Jupyter notebook through Mordor.

This is a Gate 3A QA run. Do not edit repo files. Do not create or modify an ipynb file directly. Do not run a cold raw CSV build or scan. Your job is to author notebook cells and insert them into the active live notebook through Mordor.

Use this exact mordorctl binary:
{mordorctl}

Required first actions, in this order:
1. `{mordorctl} notebook context --json`
2. `{mordorctl} memory list --json`
3. `{mordorctl} repo status --repo {nav_repo} --json`
4. Inspect the repo with `rg` to discover the current hot stock/ETF universe parquet/cache loading path and supporting data-update utility. Search for hot-universe, intraday research cache, and cache management terms. Record what you found in your transcript by showing the commands and relevant paths.

Then author four generated cell-source files under `{temp_dir}`:

- `audit.md`: a short audit section. Its first line must be `## Mordor generated: audit`.
- `panel_load.py`: load the fresh existing stock/ETF panel from the discovered hot parquet/cache path without cold-scanning raw CSV, display cache metadata and latest-date sample rows, and register the loaded panel with Mordor if the `mordor` object exists. Its first line must be `# Mordor generated: panel load`.
- `bounded_backtest.py`: use the loaded notebook variables, derive the symbol universe from the loaded data, run a small lagged bounded QA backtest, display a compact summary and tail rows, and register the output with Mordor if possible. Its first line must be `# Mordor generated: bounded backtest`.
- `chart_render.py`: render a chart from the bounded backtest output in the notebook. Its first line must be `# Mordor generated: chart render`.

The generated cells may be pragmatic and bounded, but they must be real notebook cells that can execute in the active notebook. Do not use a pasted ticker list. Derive samples from the loaded data. Do not rely on any analysis cells already present in the notebook.

Do not draft long cell source in chat. Use a single Python heredoc command with `pathlib.Path(...).write_text(...)` to write the four files, then proceed immediately. Keep each code cell concise and bounded.

Before inserting, run a shell command that prints the first line of each generated file so the transcript contains the generated-cell markers.

Insert the files through Mordor with these commands:

- `{mordorctl} cell insert --type markdown --file {temp_dir}/audit.md --json`
- `{mordorctl} cell insert --type code --file {temp_dir}/panel_load.py --json`
- `{mordorctl} cell insert --type code --file {temp_dir}/bounded_backtest.py --json`
- `{mordorctl} cell insert --type code --file {temp_dir}/chart_render.py --json`

  After all four inserts return `ok: true` and `persisted_notebook: true`,
  print `{DONE_MARKER} {session_name}`.
"""


def launch_notebook_and_bootstrap(
    *,
    page: Page,
    base_url: str,
    jupyter_prefix: str,
    notebook_rel: str,
    workspace_id: str,
    artifact_dir: Path,
) -> dict[str, Any]:
    console_path = artifact_dir / "browser_console.jsonl"
    network_path = artifact_dir / "network_requests.jsonl"
    console_errors: list[str] = []
    request_urls: list[str] = []

    def on_console(msg: Any) -> None:
        row = {"type": msg.type, "text": msg.text, "location": msg.location}
        append_jsonl(console_path, row)
        if msg.type == "error":
            console_errors.append(msg.text)

    def on_request(request: Any) -> None:
        request_urls.append(request.url)
        append_jsonl(network_path, {"method": request.method, "url": request.url})

    page.on("console", on_console)
    page.on("request", on_request)
    page.goto(
        f"{base_url.rstrip('/')}{jupyter_prefix}/lab/workspaces/{workspace_id}/tree/{notebook_rel}?reset",
        wait_until="domcontentloaded",
        timeout=60_000,
    )
    notebook = page.locator(".jp-Notebook:visible").first
    notebook.wait_for(timeout=60_000)
    page.keyboard.press("Escape")
    before_cells = notebook.locator(".jp-Cell").count()
    bootstrap_error: str | None = None
    for _ in range(3):
        try:
            code_cell = notebook.locator(".jp-CodeCell").first
            code_cell.scroll_into_view_if_needed(timeout=10_000)
            code_cell.click(timeout=30_000)
            page.keyboard.press("Control+Enter")
            page.locator("[data-mordor-action='context']").wait_for(timeout=35_000)
            bootstrap_error = None
            break
        except Exception as exc:
            bootstrap_error = f"{type(exc).__name__}: {exc}"
            time.sleep(2.0)
    if bootstrap_error:
        raise RuntimeError(f"bootstrap cell did not render Mordor panel: {bootstrap_error}")
    page.locator("[data-mordor-action='context']").click(timeout=30_000)
    page.wait_for_function(
        """() => {
            const out = document.querySelector('[data-mordor-output]');
            return out && out.textContent.includes('gate3a_seed');
        }""",
        timeout=45_000,
    )
    return {
        "before_cells": before_cells,
        "console_errors": console_errors,
        "request_urls": request_urls,
    }


def browser_save(page: Page, wait_seconds: float = 2.5) -> None:
    page.keyboard.press("Control+S")
    time.sleep(wait_seconds)


def open_notebook_page(
    *,
    page: Page,
    base_url: str,
    jupyter_prefix: str,
    notebook_rel: str,
    workspace_id: str,
    reset: bool = False,
) -> None:
    suffix = "?reset" if reset else ""
    page.goto(
        f"{base_url.rstrip('/')}{jupyter_prefix}/lab/workspaces/{workspace_id}/tree/{notebook_rel}{suffix}",
        wait_until="domcontentloaded",
        timeout=60_000,
    )
    page.locator(".jp-Notebook:visible").first.wait_for(timeout=60_000)


def wait_for_generated_cells(page: Page, minimum: int = 4, timeout_s: float = 120.0) -> int:
    deadline = time.time() + timeout_s
    last_count = 0
    while time.time() < deadline:
        count = page.locator(".jp-Cell").filter(has_text=GENERATED_MARKER).count()
        last_count = count
        if count >= minimum:
            return count
        time.sleep(2.0)
    return last_count


def notebook_generated_cell_count(path: Path) -> int:
    if not path.exists():
        return 0
    nb = nbformat.read(path, as_version=4)
    return sum(1 for cell in nb.cells if GENERATED_MARKER in cell_source(cell))


def ensure_generated_cells_visible(
    *,
    page: Page,
    base_url: str,
    jupyter_prefix: str,
    notebook_rel: str,
    workspace_id: str,
    notebook_path: Path,
    minimum: int = 4,
) -> dict[str, Any]:
    first_count = wait_for_generated_cells(page, minimum=minimum, timeout_s=3)
    file_count = notebook_generated_cell_count(notebook_path)
    reloaded = False
    final_count = first_count
    if first_count < minimum and file_count >= minimum:
        reloaded = True
        open_notebook_page(
            page=page,
            base_url=base_url,
            jupyter_prefix=jupyter_prefix,
            notebook_rel=notebook_rel,
            workspace_id=f"{workspace_id}-verify",
            reset=True,
        )
        final_count = wait_for_generated_cells(page, minimum=minimum, timeout_s=60)
    return {
        "visible_before_reload": first_count,
        "saved_notebook_generated_cell_count": file_count,
        "reloaded_for_file_backed_insert": reloaded,
        "visible_after_reload": final_count,
        "ok": final_count >= minimum,
    }


def try_run_all_cells(page: Page, timeout_s: float = 300.0) -> dict[str, Any]:
    started = time.time()
    errors: list[str] = []
    commands = [
        ("Control+Shift+C", "run all cells", "Enter"),
        ("Control+Shift+C", "run all", "Enter"),
    ]
    for shortcut, query, submit in commands:
        try:
            page.keyboard.press(shortcut)
            time.sleep(0.5)
            page.keyboard.type(query)
            page.keyboard.press(submit)
            break
        except Exception as exc:
            errors.append(str(exc))
    deadline = started + timeout_s
    while time.time() < deadline:
        busy = page.locator(".jp-Notebook.jp-mod-commandMode .jp-InputArea-editor.jp-mod-focused").count()
        running = page.locator(".jp-Notebook .jp-CodeCell.jp-mod-running").count()
        if running == 0 and time.time() - started > 8:
            return {"ok": True, "elapsed_s": round(time.time() - started, 2), "busy_count": busy}
        time.sleep(2.0)
    return {"ok": False, "elapsed_s": round(time.time() - started, 2), "errors": errors}


def copy_if_exists(src: Path, dst: Path) -> bool:
    if not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def capture_agent(mordorctl: Path, nav_repo: Path, session_name: str, lines: int = 5000) -> dict[str, Any]:
    proc = run(
        [
            str(mordorctl),
            "agent",
            "capture",
            "--repo",
            str(nav_repo),
            "--session",
            session_name,
            "--lines",
            str(lines),
            "--json",
        ],
        cwd=nav_repo,
        timeout=15,
    )
    if proc.returncode != 0:
        return {"ok": False, "stdout": proc.stdout, "stderr": proc.stderr}
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError:
        return {"ok": False, "stdout": proc.stdout, "stderr": proc.stderr, "error": "invalid JSON"}


def wait_for_agent_done(
    *,
    mordorctl: Path,
    nav_repo: Path,
    session_name: str,
    notebook_path: Path,
    timeout_s: float,
    poll_s: float,
    artifact_dir: Path,
) -> dict[str, Any]:
    deadline = time.time() + timeout_s
    last_capture: dict[str, Any] = {}
    while time.time() < deadline:
        last_capture = capture_agent(mordorctl, nav_repo, session_name)
        text = str(last_capture.get("text", ""))
        write_json(artifact_dir / "agent_capture_latest.json", last_capture)
        lowered_text = text.lower()
        persisted_in_transcript = (
            text.count("persisted_notebook") >= 4
            or "persisted all four" in lowered_text
            or "all four mordor inserts returned" in lowered_text
            or "all four inserts returned" in lowered_text
        )
        persisted_in_notebook = notebook_generated_cell_count(notebook_path) >= 4
        if text.count(DONE_MARKER) >= 2 and (persisted_in_transcript or persisted_in_notebook):
            return {"ok": True, "capture": last_capture}
        if "mordorctl:" in text and "No active Mordor runtime bridge" in text:
            return {"ok": False, "error": "agent could not reach active Mordor runtime bridge", "capture": last_capture}
        time.sleep(poll_s)
    return {"ok": False, "error": "timed out waiting for Gate 3A completion marker", "capture": last_capture}


def transcript_words(text: str) -> str:
    """Normalize wrapped tmux/Codex transcript text for command evidence checks."""

    return re.sub(r"[^a-z0-9_./-]+", " ", text.lower())


def verify_transcript(text: str) -> tuple[bool, list[str], dict[str, Any]]:
    lowered_text = text.lower()
    words = transcript_words(text)
    done_marker_count = text.count(DONE_MARKER)
    applied_live_count = text.count("applied_live")
    persisted_notebook_count = text.count("persisted_notebook")
    generated_marker_count = text.count(GENERATED_MARKER)
    expected_generated_files = ("audit.md", "panel_load.py", "bounded_backtest.py", "chart_render.py")
    generated_file_reference_count = sum(1 for filename in expected_generated_files if filename in text)
    cell_insert_count = words.count("mordorctl cell insert")
    marker_semantic_evidence = (
        generated_file_reference_count == len(expected_generated_files)
        and (
            generated_marker_count >= 3
            or "markers are present" in lowered_text
            or "marker check passed" in lowered_text
            or "markers look correct" in lowered_text
        )
    )
    persisted_semantic_evidence = (
        persisted_notebook_count >= 4
        or "persisted all four" in lowered_text
        or "all four mordor inserts returned" in lowered_text
        or "all four inserts returned" in lowered_text
    )
    checks = {
        "done_marker_count": done_marker_count,
        "notebook_context": "mordorctl notebook context" in words or "notebook context" in words,
        "memory": "mordorctl memory list" in words or "mordorctl memory inspect" in words,
        "repo_status_or_diff": "mordorctl repo status" in words or "mordorctl repo diff" in words,
        "repo_discovery": any(
            token in text
            for token in (
                "hot_universe.py",
                "navstrategies/utilities/hot_universe.py",
                "manage_intraday_research_cache.py",
                "scripts/manage_intraday_research_cache.py",
                "intraday_research_universe.parquet",
                "sharadar_sep_price_volume_panel_latest.parquet",
            )
        ),
        "cell_insert_count": cell_insert_count,
        "generated_marker_count": generated_marker_count,
        "generated_file_reference_count": generated_file_reference_count,
        "applied_live_count": applied_live_count,
        "persisted_notebook_count": persisted_notebook_count,
        "marker_semantic_evidence": marker_semantic_evidence,
        "persisted_semantic_evidence": persisted_semantic_evidence,
    }
    failures = []
    if done_marker_count < 2:
        failures.append("missing completion marker printed after prompt")
    if not checks["notebook_context"]:
        failures.append("missing mordorctl notebook context evidence")
    if not checks["memory"]:
        failures.append("missing mordorctl memory evidence")
    if not checks["repo_status_or_diff"]:
        failures.append("missing mordorctl repo status/diff evidence")
    if not checks["repo_discovery"]:
        failures.append("missing rg repo/data discovery evidence")
    if int(checks["cell_insert_count"]) < 4:
        failures.append("fewer than four mordorctl cell insert commands found")
    if not marker_semantic_evidence:
        failures.append("missing generated-file marker evidence in transcript")
    if not persisted_semantic_evidence:
        failures.append("fewer than four persisted_notebook results in transcript")
    return not failures, failures, checks


def cell_source(cell: Any) -> str:
    return str(cell.get("source", ""))


def output_kinds(cell: Any) -> list[str]:
    kinds: list[str] = []
    for output in cell.get("outputs", []) or []:
        output_type = output.get("output_type")
        if output_type:
            kinds.append(str(output_type))
        data = output.get("data") or {}
        for key in data:
            kinds.append(str(key))
    return sorted(set(kinds))


def classify_generated_cell(source: str) -> str:
    lowered = source.lower()
    first_line = lowered.splitlines()[0] if lowered.splitlines() else ""
    if "chart render" in first_line:
        return "chart"
    if "bounded backtest" in first_line:
        return "backtest"
    if "panel load" in first_line:
        return "panel_load"
    if "audit" in first_line:
        return "audit"
    if "chart render" in lowered or "chart" in lowered:
        return "chart"
    if "bounded backtest" in lowered or "backtest" in lowered:
        return "backtest"
    if "panel load" in lowered or "metadata" in lowered or "latest-date" in lowered:
        return "panel_load"
    if "audit" in lowered:
        return "audit"
    return "unknown"


def build_inserted_manifest(notebook_path: Path, transcript_text: str) -> dict[str, Any]:
    nb = nbformat.read(notebook_path, as_version=4)
    cells: list[dict[str, Any]] = []
    for index, cell in enumerate(nb.cells):
        source = cell_source(cell)
        if GENERATED_MARKER not in source:
            continue
        first_line = source.splitlines()[0] if source.splitlines() else ""
        sha = hashlib.sha256(source.encode("utf-8")).hexdigest()
        role = classify_generated_cell(source)
        cells.append(
            {
                "index": index,
                "cell_type": cell.cell_type,
                "role": role,
                "first_line": first_line,
                "sha256": sha,
                "output_count": len(cell.get("outputs", []) or []),
                "output_kinds": output_kinds(cell),
                "transcript_mentions_first_line": first_line in transcript_text,
                "transcript_mentions_marker": GENERATED_MARKER in transcript_text,
            }
        )
    roles = sorted({cell["role"] for cell in cells})
    role_counts = {role: sum(1 for cell in cells if cell["role"] == role) for role in roles}
    rendered_outputs = {
        "metadata_table": any(cell["role"] == "panel_load" and cell["output_count"] > 0 for cell in cells),
        "latest_sample": any(cell["role"] == "panel_load" and cell["output_count"] > 0 for cell in cells),
        "backtest_summary": any(cell["role"] == "backtest" and cell["output_count"] > 0 for cell in cells),
        "chart": any(cell["role"] == "chart" and "image/png" in cell["output_kinds"] for cell in cells),
    }
    return {
        "cells": cells,
        "roles": roles,
        "role_counts": role_counts,
        "cell_count": len(cells),
        "rendered_outputs": rendered_outputs,
    }


def verify_notebook_evidence(starting_path: Path, final_path: Path, transcript_text: str) -> tuple[bool, list[str], dict[str, Any]]:
    start_nb = nbformat.read(starting_path, as_version=4)
    final_nb = nbformat.read(final_path, as_version=4)
    manifest = build_inserted_manifest(final_path, transcript_text)
    failures: list[str] = []
    if len(final_nb.cells) <= len(start_nb.cells):
        failures.append("final notebook does not have more cells than starting notebook")
    required_roles = {"audit", "panel_load", "backtest", "chart"}
    missing_roles = sorted(required_roles.difference(manifest["roles"]))
    if missing_roles:
        failures.append(f"missing generated cell roles: {', '.join(missing_roles)}")
    if manifest["cell_count"] != 4:
        failures.append(f"expected exactly 4 generated cells, found {manifest['cell_count']}")
    duplicate_roles = sorted(role for role in required_roles if manifest["role_counts"].get(role, 0) != 1)
    if duplicate_roles:
        failures.append(f"expected exactly one generated cell for roles: {', '.join(duplicate_roles)}")
    for key, value in manifest["rendered_outputs"].items():
        if not value:
            failures.append(f"missing rendered output: {key}")
    if not all(cell["transcript_mentions_marker"] for cell in manifest["cells"]):
        failures.append("transcript does not mention generated marker")
    return not failures, failures, manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Gate 3A QA: prove Codex generates and inserts navstrategies notebook cells through Mordor.")
    parser.add_argument("--base-url", default="http://127.0.0.1:5011")
    parser.add_argument("--jupyter-prefix", default="/jlab")
    parser.add_argument("--nav-repo", type=Path, default=DEFAULT_NAV_REPO)
    parser.add_argument("--artifact-dir", type=Path)
    parser.add_argument("--chromium", default=DEFAULT_CHROMIUM)
    parser.add_argument("--agent-timeout-seconds", type=float, default=900.0)
    parser.add_argument("--poll-seconds", type=float, default=15.0)
    parser.add_argument(
        "--codex-command",
        default="codex --sandbox danger-full-access --ask-for-approval never",
        help="Codex command used inside the tmux agent for unattended QA.",
    )
    parser.add_argument("--skip-browser-execute", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    nav_repo = args.nav_repo.expanduser().resolve()
    stamp = utc_stamp()
    artifact_dir = (args.artifact_dir or nav_repo / "milestones" / "mordor_remote_qa" / stamp).expanduser().resolve()
    artifact_dir.mkdir(parents=True, exist_ok=True)
    screenshots_dir = artifact_dir / "screenshots"
    tmux_dir = artifact_dir / "tmux"
    notebooks_dir = artifact_dir / "notebooks"
    for path in (screenshots_dir, tmux_dir, notebooks_dir):
        path.mkdir(parents=True, exist_ok=True)

    mordorctl = nav_repo / ".venv" / "bin" / "mordorctl"
    if not mordorctl.exists():
        mordorctl = Path(sys.executable).resolve().parent / "mordorctl"
    session_name = f"mordor-gate3a-{stamp.lower()}"
    workspace_id = session_name
    notebook_path = create_thin_starting_notebook(nav_repo, stamp)
    notebook_rel = notebook_path.relative_to(nav_repo / "notebooks").as_posix()
    starting_artifact = artifact_dir / "starting_notebook.ipynb"
    final_artifact = artifact_dir / "final_notebook.ipynb"
    prompt_path = artifact_dir / "agent_prompt.txt"
    summary_path = artifact_dir / "summary.json"
    manifest_path = artifact_dir / "inserted_cells_manifest.json"

    summary: dict[str, Any] = {
        "ok": False,
        "base_url": args.base_url,
        "jupyter_prefix": "/" + args.jupyter_prefix.strip("/"),
        "navstrategies_repo": str(nav_repo),
        "artifact_dir": str(artifact_dir),
        "scratch_notebook": str(notebook_path),
        "starting_notebook": str(starting_artifact),
        "final_notebook": str(final_artifact),
        "mordorctl": str(mordorctl),
        "codex_command": args.codex_command,
        "tmux_session": session_name,
        "jupyter_workspace": workspace_id,
        "gates": {"agent_generated_notebook": "fail", "fresh_universe": "fail"},
        "failures": [],
    }

    start_failures = validate_starting_notebook(notebook_path)
    copy_if_exists(notebook_path, starting_artifact)
    if start_failures:
        summary["failures"].extend(f"starting notebook invalid: {failure}" for failure in start_failures)
        write_json(summary_path, summary)
        print(json.dumps(summary, indent=2, sort_keys=True))
        return 1

    prompt_path.write_text(prompt_text(nav_repo, mordorctl, session_name, stamp), encoding="utf-8")
    write_json(artifact_dir / "environment.json", {"created_at": datetime.now(timezone.utc).isoformat(), "argv": sys.argv})

    base_url = args.base_url.rstrip("/")
    jupyter_prefix = "/" + args.jupyter_prefix.strip("/")
    page_evidence: dict[str, Any] = {}
    transcript_text = ""

    with sync_playwright() as p:
        browser = p.chromium.launch(
            executable_path=args.chromium,
            headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage"],
        )
        page = browser.new_page(viewport={"width": 1440, "height": 1000})
        try:
            page_evidence = launch_notebook_and_bootstrap(
                page=page,
                base_url=base_url,
                jupyter_prefix=jupyter_prefix,
                notebook_rel=notebook_rel,
                workspace_id=workspace_id,
                artifact_dir=artifact_dir,
            )
            page.screenshot(path=str(screenshots_dir / "bootstrap_panel.png"), full_page=True)

            run(["tmux", "kill-session", "-t", session_name], timeout=5)
            start_proc = run(
                [
                    str(mordorctl),
                    "agent",
                    "start",
                    "--repo",
                    str(nav_repo),
                    "--session",
                    session_name,
                    "--codex-command",
                    args.codex_command,
                    "--json",
                ],
                cwd=nav_repo,
                timeout=45,
            )
            write_json(
                artifact_dir / "agent_start.json",
                {"returncode": start_proc.returncode, "stdout": start_proc.stdout, "stderr": start_proc.stderr},
            )
            if start_proc.returncode != 0:
                summary["failures"].append("failed to start Codex tmux agent")
            else:
                send_proc = run(
                    [
                        str(mordorctl),
                        "agent",
                        "send",
                        "--repo",
                        str(nav_repo),
                        "--session",
                        session_name,
                        "--codex-command",
                        args.codex_command,
                        "--file",
                        str(prompt_path),
                        "--json",
                    ],
                    cwd=nav_repo,
                    timeout=45,
                )
                write_json(
                    artifact_dir / "agent_send.json",
                    {"returncode": send_proc.returncode, "stdout": send_proc.stdout, "stderr": send_proc.stderr},
                )
                if send_proc.returncode != 0:
                    summary["failures"].append("failed to send Gate 3A prompt to Codex tmux agent")
                else:
                    done = wait_for_agent_done(
                        mordorctl=mordorctl,
                        nav_repo=nav_repo,
                        session_name=session_name,
                        notebook_path=notebook_path,
                        timeout_s=args.agent_timeout_seconds,
                        poll_s=args.poll_seconds,
                        artifact_dir=artifact_dir,
                    )
                    if not done.get("ok"):
                        summary["failures"].append(str(done.get("error", "agent did not complete")))
                    capture = done.get("capture") or capture_agent(mordorctl, nav_repo, session_name)
                    transcript_text = str(capture.get("text", ""))
                    transcript_path = tmux_dir / f"{session_name}.log"
                    transcript_path.write_text(transcript_text, encoding="utf-8")
                    summary["transcript"] = str(transcript_path)

                    insertion_evidence = ensure_generated_cells_visible(
                        page=page,
                        base_url=base_url,
                        jupyter_prefix=jupyter_prefix,
                        notebook_rel=notebook_rel,
                        workspace_id=workspace_id,
                        notebook_path=notebook_path,
                        minimum=4,
                    )
                    summary["notebook_insertion"] = insertion_evidence
                    summary["generated_cells_visible_in_browser"] = insertion_evidence["visible_after_reload"]
                    page.screenshot(path=str(screenshots_dir / "after_agent_insert.png"), full_page=True)

                    if insertion_evidence["ok"] and not args.skip_browser_execute:
                        execute_result = try_run_all_cells(page)
                        write_json(artifact_dir / "browser_execute.json", execute_result)
                    if insertion_evidence["ok"]:
                        browser_save(page)
                    page.screenshot(path=str(screenshots_dir / "after_execute_save.png"), full_page=True)
                    copy_if_exists(notebook_path, final_artifact)
        except Exception as exc:
            summary["failures"].append(f"browser/agent run exception: {type(exc).__name__}: {exc}")
            try:
                page.screenshot(path=str(screenshots_dir / "failure.png"), full_page=True)
            except Exception:
                pass
        finally:
            browser.close()

    summary["browser"] = {
        "before_cells": page_evidence.get("before_cells"),
        "console_error_count": len(page_evidence.get("console_errors", [])),
        "raw_bridge_requests": [
            url
            for url in page_evidence.get("request_urls", [])
            if "127.0.0.1" in url and not any(port in url for port in (":5011", ":5012", ":8890"))
        ],
    }
    if not final_artifact.exists():
        summary["failures"].append("final notebook artifact was not saved")

    transcript_ok, transcript_failures, transcript_checks = verify_transcript(transcript_text)
    summary["transcript_checks"] = transcript_checks
    if not transcript_ok:
        summary["failures"].extend(transcript_failures)

    notebook_ok = False
    manifest: dict[str, Any] = {"cells": [], "rendered_outputs": {}}
    if final_artifact.exists():
        notebook_ok, notebook_failures, manifest = verify_notebook_evidence(starting_artifact, final_artifact, transcript_text)
        if not notebook_ok:
            summary["failures"].extend(notebook_failures)
    write_json(manifest_path, manifest)
    summary["inserted_cells_manifest"] = str(manifest_path)
    summary["rendered_outputs"] = manifest.get("rendered_outputs", {})
    insertion_ok = bool(summary.get("notebook_insertion", {}).get("ok"))
    summary["gates"]["agent_generation"] = "pass" if transcript_ok else "fail"
    summary["gates"]["notebook_insertion"] = "pass" if insertion_ok else "fail"
    summary["gates"]["notebook_execution"] = "pass" if notebook_ok else "fail"
    summary["gates"]["agent_generated_notebook"] = "pass" if transcript_ok and insertion_ok and notebook_ok else "fail"
    summary["gates"]["fresh_universe"] = "pass" if manifest.get("rendered_outputs", {}).get("metadata_table") else "fail"
    summary["ok"] = summary["gates"]["agent_generated_notebook"] == "pass" and summary["gates"]["fresh_universe"] == "pass"

    lines = [
        "# Mordor Gate 3A QA Summary",
        "",
        f"- ok: `{summary['ok']}`",
        f"- tmux session: `{session_name}`",
        f"- scratch notebook: `{notebook_path}`",
        f"- final notebook: `{final_artifact}`",
        "",
        "| Gate | Status |",
        "|---|---|",
    ]
    for gate, status in summary["gates"].items():
        lines.append(f"| `{gate}` | `{status}` |")
    if summary["failures"]:
        lines.extend(["", "## Failures", ""])
        lines.extend(f"- {failure}" for failure in summary["failures"])
    (artifact_dir / "summary.md").write_text("\n".join(lines), encoding="utf-8")
    write_json(summary_path, summary)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0 if summary["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
